version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/local/php/Dockerfile
    container_name: app
    volumes:
      - .:/app
    ports:
      - '80:8080'
    depends_on:
      - mysql
      - mysql_test
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - mysql-local-data:/var/lib/mysql
      - ./docker/local/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3306:3306
  mysql_test:
    image: mysql:8.0
    container_name: mysql_test
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: 'test'
      MYSQL_USER: 'testuser'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_TCP_PORT: 3307
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - mysql-local-test-data:/var/lib/mysql
      - ./docker/local/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - 3307:3306
    expose:
      - 3307
volumes:
    mysql-local-data:
        driver: local
    mysql-local-test-data:
        driver: local